### ISSUE TITLE
Can you provide RDA data in text-based formats?

### ISSUE THREAD

**Issue by LinguList** [AnnaDiNatale/colex_affective#1]
Reading the data in R is not possible with all distributions, since this format depends on the R versions you use. So storing the original data (and sharing it) in CSV files is recommended to guarantee replicability.

**Comment by AnnaDiNatale** [comment]
Sure! I will do it soon! Thank you for your remark

**Comment by LinguList** [comment]
Thanks for the nice paper, I enjoyed reading it a lot. BTW: you know 
about our attempts to standardize data on norms and relations with the 
concepticon, so they would be automatically linked up with clics?

https://digling.org/norare/

I assume that this might come in handy for any future work, where you'd 
have to map between CLICS words and all kinds of ratings.

**Comment by AnnaDiNatale** [comment]
Thank you! I found your work very inspiring. 
I knew about concepticon, but not about NoRaRe. Thank you for the info.
Where possible, I also provided a .csv version of the files. I hope you will find them useful.
Best,
Anna

**Comment by LinguList** [comment]
Thanks a lot!
